### ISSUE TITLE
Creating a customer without notifying them

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor-dashboard#202]
### What I'm trying to achieve
I would like to add a customer via the dashboard without sending them an email to change their password. We get larger orders via email or individual discussions and I would like to add these orders via the dashboard so that we have a single order management system. This password reset email is very annoying, as we don't actually use the login feature for customers.

### Describe a proposed solution
Just one checkbox for enabling/disabling the password email. I think the mutation just needs to set "sendPasswordEmail" to false

### Other solutions I've tried and won't work
…

**Comment by maarcingebala** [comment]
Thanks for reporting that. Our API allows for creating customers without sending the password reset link. The problem is only in the dashboard which requires providing this link and to make things worse this is not handled properly, so this view is now broken. We'll take a look at this. There should be some checkbox to decide if you want to send the email. Also, there should be a way to provide this URL in UI.

**Comment by maarcingebala** [comment]
@JannikZed I've opened #204 for it to describe all required design and frontend changes.
