### ISSUE TITLE
Link to demo causes a 404 error

### ISSUE THREAD

**Issue by petedermott** [mirumee/saleor-dashboard#232]
The link to the [current demo of the new Saleor dashboard](https://demo.getsaleor.com/dashboard/next/) causes a 404 error

**Comment by maarcingebala** [comment]
That's right, the dashboard is no longer available under this link since it's not hosted by Django anymore. The new demo address is: https://pwa.saleor.io/dashboard/.

Did you find this link on some of our websites or you just knew it/had it saved? If we're still using this link anywhere, it should be fixed.

**Comment by petedermott** [comment]
Its on https://github.com/mirumee/saleor-dashboard#demo and https://github.com/mirumee/saleor#dashboard-20

**Comment by maarcingebala** [comment]
I've updated the links, thanks for reporting!

**Comment by indiejoseph** [comment]
Hi, i just clone a latest master branch and run on a server, the storefront is works fine, but i cannot access /dashboard, there've shown 404 error, https://www.national-calamity.store/dashboard/

**Comment by maarcingebala** [comment]
Hey @indiejoseph, the old dashboard that was available at `/dashboard` has been removed from Saleor ([see is the issue](https://github.com/mirumee/saleor/issues/4463) about it). Dashboard 2.0 (this repo) is now the official dashboard for Saleor. Please read [these instructions](https://github.com/mirumee/saleor-dashboard#getting-started) about how to set it up.
