### ISSUE TITLE
Production Build creates single large file

### ISSUE THREAD

**Issue by nikolas310** [mirumee/saleor-dashboard#589]
`npm run build` creates dashboard.xxxx.js file about 10mb. How to fix

```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  dashboard (10.2 MiB)
      dashboard.7aa3678e24c3e261447c.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

```

**Comment by karolkielecki** [comment]
@nikolas310 Hi there! Thanks for pointing this out. It's a known issue, but we currently don't have time to fix it. Please ignore the warnings for now. If you would like to contribute to the project, pull requests are welcome.

**Comment by vinit03** [comment]
Around 80% of size is due to the internationalisation (all the language options provided). I removed all other languages (except for EN) from the src/components/Locale/Locale.tsx (and used Locale.EN in Locale.test.ts) and the size reduced to 1.3MB and 339kb with Gzipped.  I have also lazy loaded all components for better code splitting.

**Comment by nikolas310** [comment]
@vinit03 Thanks. Its a temporary solution. But need to fixed

**Comment by eaglesemanation** [comment]
I want to work on that. To my understanding I would need to load locales asynchronously and configure webpack to include locales in bundle, right?
