### ISSUE TITLE
Can't Login to Saleor Dashboard (Dev)

### ISSUE THREAD

**Issue by MLSkye** [mirumee/saleor-dashboard#683]
### What I'm trying to achieve
Log in to saleor dashboard using

- email: admin@example.com
- password: 'admin' or 'saleor'

### Steps to reproduce the problem

- follow the steps to install on windows

- start the saleor-api, dashboard and storefront

-  visit http://localhost:9000/ 

### What I expected to happen
![Screenshot_2020-08-31 Dashboard Saleor e-commerce(1)](https://user-images.githubusercontent.com/52390439/91731581-e6eeef00-eb9e-11ea-98b7-dfd5f6e17e9b.png)

### Screenshots

![Screenshot_2020-08-31 Dashboard Saleor e-commerce](https://user-images.githubusercontent.com/52390439/91731614-f2dab100-eb9e-11ea-8258-112b559a0b83.png)

### Console output

Here's the console error:
[console-export-2020-8-31_15-33-54.txt](https://github.com/mirumee/saleor-dashboard/files/5150882/console-export-2020-8-31_15-33-54.txt)

**System information**

Operating system: 

- Windows 10 Pro (v1903)

Browser:
- Firefox Developer Edition 79.0b6 (64-bit)

**Comment by ijkml** [comment]
> did you end up solving this problem ?

Yeah, I think I did. I don't remember now, though 😅.

**Comment by Mahboob-A** [comment]
**### Here's the solution:** 


Once you have run the local setup, please run `createsuperuser` command to setup the login credentials in order to login to the dashboard page. 

If your local setup is running, then run `docker compose stop` to stop the local setup and run the below command: 

`docker compose run --rm api python3 manage.py createsuperuser`

enter demo email and password (do not put any space after the `Email` word in the console), 

now up the local setup and you can successfully login to the dashboard page.
