### ISSUE TITLE
The password is shown on the page source.

### ISSUE THREAD

**Issue by zlosliwa** [mirumee/saleor-dashboard#756]
### What I'm trying to achieve
After typing in a password in the field I can see it on the page source.

### Steps to reproduce the problem
1.  Go to the Dashboard 
2.  Fill the filed `password` 
3.  Inspect the element.

### Actual result 
The password is shown on the page source. 

### What I expected to happen
Password should not be shown on the page source - I have compared this with other sites like Amazon, Shopify, etc. and I could not find this solution on other pages this is why I decided to report this.

### Screenshots

![image](https://user-images.githubusercontent.com/29308910/95661197-cca91900-0b2d-11eb-8fe8-550c152dbc88.png)

**System information**

Operating system: 
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [x] Chrome
- [ ] Edge
- [x] Other

**Comment by karolkielecki** [comment]
@zlosliwa Thanks for reporting! I've passed the issue to our team.

**Comment by saschametz** [comment]
@zlosliwa That's normal and I wouldn't consider it an issue since the user input needs to be send to the API. The important thing is to use HTTPS (which Saleor does) because then all traffic is encrypted

 You can see this in other established React apps as well:
- https://app.netlify.com/login/email
- https://www.airbnb.com/
