### ISSUE TITLE
Add Weight Based Rate Issue

### ISSUE THREAD

**Issue by zatin009** [mirumee/saleor-dashboard#77]
### What I'm trying to achieve
Able to Add Weight Rate
### Steps to reproduce the problem
1. Click on Configure in Dashboard
2. Shipping Method
3. Add shipping Zone
4. Add Weight Based Rate
The the data is saved in "Price Based Rates" insteads

### What I expected to happen
Add Weight Based Rate 
### Screenshots
![1](https://user-images.githubusercontent.com/40449637/61855263-f60a6480-aee9-11e9-8790-47d14f194052.PNG)
![2](https://user-images.githubusercontent.com/40449637/61855269-f99deb80-aee9-11e9-8989-573d01916ed2.PNG)

**Comment by maarcingebala** [comment]
@fowczarek when you have time, please investigate whether this is backend or frontend issue.

**Comment by zatin009** [comment]
@maarcingebala Yes, I'm configuring it.

**Comment by fowczarek** [comment]
@maarcingebala  
It's a frontend issue.

![image](https://user-images.githubusercontent.com/43955230/63416866-9166fa80-c400-11e9-9fd5-50a2208d23ea.png)

![image](https://user-images.githubusercontent.com/43955230/63416892-9deb5300-c400-11e9-8b76-19a5f8d9d1a8.png)

Frontend should send `type: "WEIGHT"` instead of  `type: "PRICE"`

**Comment by zatin009** [comment]
Yes it is the frontend issues. I configured & tested. We have the add the below code 
_"type:
                params.type === ShippingMethodTypeEnum.WEIGHT
                  ? ShippingMethodTypeEnum.WEIGHT
                  : ShippingMethodTypeEnum.PRICE
"_
in ShippingZoneRateDialog component of action: create in file " ShippingZoneDetailsDialogs.tsx"
