### ISSUE TITLE
Correct value for countryArea.

### ISSUE THREAD

**Issue by keanesf** [mirumee/saleor-dashboard#818]
### What I'm trying to achieve
Create Warehouse

### Steps to reproduce the problem
1. Fill out from for warehouse
2. Enter US in countryArea field

### What I expected to happen
Warehouse is added, but no matter what I enter countryArea field I am unable to determine correct value. 

### Http request and response from inspector

```
{"data": {"createWarehouse": {"errors": [{"code": "INVALID", "field": "countryArea", "__typename": "WarehouseError"}], "warehouse": null, "__typename": "WarehouseCreate"}}}
```

### Console output

```
// insert console output here 
```

**System information**

Operating system: 
- [ ] Windows
- [ X] Linux
- [ ] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [X ] Chrome
- [ ] Edge
- [ ] Other

**Comment by karolkielecki** [comment]
@keanesf Hey! Can try to add there `CA` or `TX`. Please let me know if it works or not. You can find the list of country areas here https://chromium-i18n.appspot.com/ssl-address.

**Comment by keanesf** [comment]
thanks, that worked.

**Comment by notpushkin** [comment]
@karolkielecki Sorry for bumping this, but perhaps `countryArea` should be a dropdown then? (And, more importantly, in https://github.com/saleor/saleor-checkout too)

**Comment by timuric** [comment]
@notpushkin we have made it dropdown in saleor checkout recently. It will only be visible for countries that require country area

**Comment by notpushkin** [comment]
@timuric That's great news! Perhaps it isn't live on https://checkout.demo.saleor.io/ yet, since it was implemented only 3 days ago (https://github.com/saleor/saleor-checkout/pull/122).

Should we discuss doing same for the dashboard on a separate issue, or is it on some kind of internal roadmap already? Also, I could take a stab at it and maybe send in a PR sometime next week (I'm not yet sure where to start though :-)

**Comment by timuric** [comment]
@notpushkin we will add it to the dashboard as well
